---
- name: Create a user in Linux
  hosts: all
  become: yes  # Run as sudo/root
  vars:
    #username: "devuser"  # Change this as needed
    username: {{user_name}}
    #user_password: "Password123!"  # Change or encrypt this using Ansible Vault
    user_password: {{password}}
    user_shell: "/bin/bash"

  tasks:
    - name: Ensure the user exists
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"  # Hash the password
        shell: "{{ user_shell }}"
        create_home: yes
        state: present

    - name: Add user to sudo group
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes
