---
- name: Install JBoss on RHEL
  hosts: all
  become: yes
  vars:
    jboss_user: jboss
    jboss_group: jboss
    jboss_home: /opt/jboss
    jboss_download_url: "https://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip"  # Replace with your desired JBoss version URL
    jboss_install_dir: /opt/jboss/jboss-as-7.1.1.Final
  tasks:
    - name: Install required packages
      yum:
        name:
          - java-1.8.0-openjdk-devel
          - unzip
        state: present
