---
- name: Install JBoss/WildFly on RHEL 9
  hosts: all
  become: yes
  vars:
    jboss_version: "25.0.0.Final"  # You can change this to the desired WildFly/JBoss version
    #jboss_download_url: "https://github.com/wildfly/wildfly/releases/download/{{ jboss_version }}/wildfly-{{ jboss_version }}.tar.gz"
    #jboss_install_dir: "/opt/wildfly"
    jboss_user: "wildfly"
    jboss_group: "wildfly"
    jboss_download_url: "https://github.com/wildfly/wildfly/releases/download/{{ jboss_version }}/wildfly-{{ jboss_version }}.tar.gz"
    jboss_install_dir: "/opt/jboss"
    #jboss_user: "jboss"
    #jboss_group: "jboss"
    jboss_home: /opt/jboss
  
  tasks:
    
    - name: Create JBoss group
      group:
        name: "{{ jboss_group }}"
        state: present
    - name: Create JBoss user
      user:
        name: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        create_home: no
        home: "{{ jboss_home }}"
        shell: /bin/bash
    - name: Create JBoss home directory
      file:
        path: "{{ jboss_home }}"
        state: directory
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        mode: '0755'
